spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://person.jjhserverworld.pe.kr:49153;instanceName=SpringApplication;DatabaseName=AdventureWorks2017
    username: SA
    password: rkwhr485!@


mybatis:
  configuration:
    call-setters-on-nulls: true
    return-instance-for-empty-row: true